### ISSUE TITLE
Usar streams

### ISSUE THREAD

**Issue by DavideCarvalho** [daviaquino87/validator-csv#1]
Se você usar fs.readFile, o arquivo inteiro vai pra memória do node, em termos de performance diminui muito, sem contar que como tem que ler o arquivo todo, IO disso é muito pesado e a performance abaixa muito

Recomendo usar streams pra ler csv

Cê pode usar alguma lib que já faz isso, como node-csv - https://csv.js.org/parse/api/stream - ou codar isso direto na sua lib

IMO seria melhor você terceirizar a parte de ler o arquivo csv pra outra lib, já que o foco da sua lib é validar o csv

**Comment by daviaquino87** [comment]
Acho totalmente valido isso de usar streams, tanto que ja fiz uma implementação para isso.
Tambem achei melhor remover o loop que verifica item a item em busca do caracter de escape, e adiconar uma regex:


function searchFileAndRemoveInformation({ filePath, separator }) {
  return new Promise((resolve, reject) => {
    const fileStream = fs.createReadStream(filePath, { encoding: "utf8" });

    const rl = readline.createInterface({
      input: fileStream,
      crlfDelay: Infinity,
    });

    let isFirstLine = true;
    let headers = [];
    let rows = [];

    rl.on("line", (line) => {
      if (isFirstLine) {
        headers = line.split(separator);
        isFirstLine = false;
      } else {
        const rowSplitted = line
          .replace(REGEX_WORD_WITH_SCAPE, (_, group) => {
            return group.replace(/,/g, "scape@scape");
          })
          .split(separator);

        const rowWithReplaceBack = rowSplitted.map((item) => {
          return item.trim().replace(/scape@scape/g, separator);
        });

        rows.push(rowWithReplaceBack);
      }
    });

    rl.on("close", () => {
      resolve({
        headers,
        rows,
      });
    });

    fileStream.on("error", (err) => {
      reject("Error reading file: " + err);
    });
  });
}`
`

**Comment by DavideCarvalho** [comment]
Invés de usar callback, for await of, talvez fique mais fácil de ler e manter

exemplo https://csv.js.org/parse/examples/async_iterator/

**Comment by daviaquino87** [comment]
modificações realizadas
