### ISSUE TITLE
Integração com libs de validação

### ISSUE THREAD

**Issue by DavideCarvalho** [daviaquino87/validator-csv#3]
Além de receber funções custom, seria legal a lib dar a possibilidade da lib obrigar o csv a seguir um schema padrão

Integrar a lib com zod seria bem legal pra isso. Segue a ideia do react hook form de receber um validationSchema - https://formik.org/docs/guides/validation#validationschema

**Comment by daviaquino87** [comment]
Adicionado yup schema
